### PR TITLE
fix header background color

### PR DESCRIPTION
**Pull request by hannessolo**
Fixes header background color on mobile when opening menu.

Test URLs:
- Before: https://main--audemarspiguet-careers--hlxsites.hlx.live/en/
- After: https://header-fix--audemarspiguet-careers--hlxsites.hlx.live/en/

### CODE REVIEW

**Review by asthabh23 — COMMENTED** [review]
Instead of using color names directly, possibly defining variables and using them could be better so as to maintain uniformity across blocks.

**Comment by asthabh23** [comment]
also, padding around the header needs a fix in mobile view.. a minor one though, possibly in a different PR or in this itself?
Franklin site:
Screenshot 2023-05-09 at 3 00 12 PM

Original site:
Screenshot 2023-05-09 at 3 00 22 PM

**Comment by ochemli** [comment]
Is 99% good enough to be able to merge PRs? I see checks have passed

**Review by ochemli — APPROVED** [review]
looks good in mobile view now 👍

**Comment by hannessolo** [comment]
> Is 99% good enough to be able to merge PRs? I see checks have passed

@ochemli yes, anything >90 will allow a merge. We should still aim for 100. In this case it looks like a cache miss for the header though (I just re-published it). Back to 100 now :)

**Pull request merged**
